

 
 
 
STATE_THIEF_EXOTICRAMPANT         <- 220    
STATE_THIEF_DISTRIBUTION         <- 221    
STATE_THIEF_NOVAREMNANT          <- 222    
STATE_THIEF_EXECUTIONERSLASH        <- 223    
STATE_THIEF_NICOLASBLACKARACHNIA       <- 224    
STATE_THIEF_BALLACREADVENT         <- 225    
STATE_WUQI				<- 230	


 
 
SKILL_THIEF_EXOTICRAMPANT         <- 220    
SKILL_THIEF_DISTRIBUTION         <- 221    
SKILL_THIEF_NOVAREMNANT          <- 222    
SKILL_THIEF_EXECUTIONERSLASH        <- 223    
SKILL_THIEF_NICOLASBLACKARACHNIA       <- 224    
SKILL_THIEF_BALLACREADVENT         <- 225    
SKILL_HUI_XIE_JING_TONG			<- 94
SKILL_WUQI				<- 230	
SKILL_LATENTABILITY				<- 254
 
 
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACK      <- 120    
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACKSHADOW     <- 121    
CUSTOM_ANI_THIEF_EXOTICRAMPANTFINALATTACK     <- 122    
CUSTOM_ANI_THIEF_EXOTICRAMPANTFINALATTACKSHADOW    <- 123    
CUSTOM_ANI_THIEF_EXOTICRAMPANTATTACKHITEND     <- 124    
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKA_BODY     <- 125    
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKB_BODY     <- 126    
CUSTOM_ANI_THIEF_DISTRIBUTION_ATTACKC_BODY     <- 127    
CUSTOM_ANI_THIEF_NOVAREMNANTJUMPCASTING_03     <- 128    
CUSTOM_ANI_THIEF_NOVAREMNANT_CASTING_BODY     <- 129    
CUSTOM_ANI_THIEF_NOVAREMNANT_JUMP_BODY      <- 130    
CUSTOM_ANI_THIEF_NOVAREMNANT_FINISH_BODY     <- 131    
CUSTOM_ANI_THIEF_NOVAREMNANT_HITEND_BODY     <- 132    
CUSTOM_ANI_THIEF_EXCS_BODY         <- 133    
CUSTOM_ANI_THIEF_CASTING01_BODY        <- 134    
CUSTOM_ANI_AccelLinksA_body							<- 135    

 
 
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTATTACK      <- 44    
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTFINALATTACK    <- 45    
CUSTOM_ATTACK_THIEF_EXOTICRAMPANTHITENDATTACK    <- 46    
CUSTOM_ATTACK_THIEF_NOVAREMNANTDASHATK      <- 47    



 


 
 
PASSIVEOBJ_SUB_STATE_0          <- 10
PASSIVEOBJ_SUB_STATE_1          <- 11
PASSIVEOBJ_SUB_STATE_2          <- 12
PASSIVEOBJ_SUB_STATE_3          <- 13
PASSIVEOBJ_SUB_STATE_4          <- 14
PASSIVEOBJ_SUB_STATE_5          <- 15
PASSIVEOBJ_SUB_STATE_6          <- 16
PASSIVEOBJ_SUB_STATE_7          <- 17
PASSIVEOBJ_SUB_STATE_8          <- 18
PASSIVEOBJ_SUB_STATE_9          <- 19
PASSIVEOBJ_SUB_STATE_10          <- 20
 

 
 
MONSTER_INDEX_THIEF_NICOLAS         <- 61531  

 
MONSTER_ZPOS_THIEF_NICOLASBLACKARACHNIA      <- 1111  
 


 
 
 

 


 
 
 

 
